### ISSUE TITLE
Update Readme doc to reflect new process

### ISSUE THREAD

**Issue by adilio** [chocolatey/choco-quickstart-scripts#11]
The main `README.md` file contains a draft of the actual QuickStart Guide V2 that we plan to PR to `docs.chocolatey.org`.

This doc needs to be updated to reflect the new process.

**Comment by adilio** [comment]
Heya @ryanrichter94, just a heads up that I've done some initial updates to the README.md in #32 .

**Comment by ryanrichter94** [comment]
During a demo of running this I noticed we need to have a good next step after the C4B Server is stood up with all of its services. Need to link out to a readme file like current QDE does to have the administrator login to the different services to change default passwords and such.

**Comment by adilio** [comment]
I'm leaving this ball firmly in your court, @ryanrichter94. 🏀 😉 

As I see it, further improvements to be made are:
- Readme file to point user int he right direction
- Possibly an update in the doc to reflect this
- Individual code block explainer blurbs should outline **parameters** as well.

Ryan, if you'd like to get a PR going for this issue, we can work form commits there.
