### ISSUE TITLE
Test Guide on Windows Server 2016,2019,2022

### ISSUE THREAD

**Issue by adilio** [chocolatey/choco-quickstart-scripts#13]
We'd like to be able to use the QuickStart Guide on ALL currently-supported Windows Server OS's. This guide is _meant_ to be opinionated, and as such we have no intention of supporting non-WMF/PowerShell 5.1 devices.

As such, we're looking to test the Guide on:

- [x] Windows Server 2016
- [x] Windows Server 2019
- [x] Windows Server 2022

We're not as worried about 1809-20H2 releases, as supporting major version OS's above and below them should cover those as well.

**Comment by ryanrichter94** [comment]
Ran through this on windows 2022 using the default certificate the Set-SslSecurity.ps1 script creates. Worked fine besides running into #57.

**Comment by ryanrichter94** [comment]
Also found #58.

**Comment by ryanrichter94** [comment]
Legacy issue. The guide has been run in all of these scenarios and deploys successfully.
