### ISSUE TITLE
Account for FIPS Environments in Setup

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/choco-quickstart-scripts#153]
## Is Your Feature Request Related To A Problem? Please describe.

Currently we do not describe that if you are running in a FIPS compliant enviornment you must enable useFipsCompliantHashes in your Chocolatey config.

## Describe The Solution. Why is it needed?

Anything run past Step 1 fails if this config value is not set when working in a FIPS compliant enviornment.

Ideal solution is to add a prompt during Step 1 execution to ask if you are running QSG setup in a FIPS compliant enviornment.

## Additional Context.

N/A

## Related Issues

* [ZenDesk Ticket](https://chocolatey.zendesk.com/agent/tickets/14889)

**Comment by JPRuskin** [comment]
Maybe instead of switches or prompts, we could check for the value of the FipsAlgorithmPolicy, and only throw an error if that is set and Choco _isn't_ configured correctly?

![Image](https://github.com/user-attachments/assets/0a4f0089-3f9f-4936-9eea-06ad9c086024)

**Comment by steviecoaster** [comment]
We'll detect the registry key for FIPs enablement, and set Chocolatey to use FIPs compliance based on that. We can bring the same logic into ClientSetup.
