### ISSUE TITLE
update Adobe Acrobat Reader DC

### ISSUE THREAD

**Issue by rajacyber** [chocolatey/choco-quickstart-scripts#156]
"Error upgrading application Adobe Acrobat Reader DC - \nWARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else

please anyone help me why im getting this error.

**Comment by ryanrichter94** [comment]
Hi @rajacyber,

Adobe Reader DC is not a package that is installed as part of setting up the [Quick Start Guide Enviornment](https://docs.chocolatey.org/en-us/guides/organizations/quick-start-guide/chocolatey-for-business-quick-start-guide#mainContent). Can I get you to please raise a support case by following the steps detailed by running `choco support` or reach out via one of our open source channels if you are not a current C4B customer that are explained here: https://chocolatey.org/support
