### ISSUE TITLE
Re-Word the Prompt for ChocoUser DB Credential Entry

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/choco-quickstart-scripts#157]
## Is Your Feature Request Related To A Problem? Please describe.
Look to create a more informative credential prompt message of what is being asked to enter. 

https://github.com/chocolatey/choco-quickstart-scripts/blob/main/Start-C4bCcmSetup.ps1#L11-L17

## Describe The Solution. Why is it needed?
Have been asked a few times what this prompt is for. Need to make it more intuitive as well as prompt to document this value. 

## Additional Context.

*[ZenDesk Ticket](https://chocolatey.zendesk.com/agent/tickets/15070)

## Related Issues

**Comment by JPRuskin** [comment]
I think this is completed, at least in the spirit of the written issue:

Current state:

```
    $DatabaseCredential = (Get-Credential -Username ChocoUser -Message 'Create a credential for the ChocolateyManagement DB user (document this somewhere)'),
```

**Comment by ryanrichter94** [comment]
Closing as @JPRuskin fixed this.
