### ISSUE TITLE
Jenkins web does not come up consistently (service is started)

### ISSUE THREAD

**Issue by adilio** [chocolatey/choco-quickstart-scripts#18]
When @ryanrichter94 runs the QuickStart scripts on his old Windows Server 2019 VM, he is intermittently seeing failures in the Jenkins website coming up.

Usually, a `Restart-Service Jenkins` brings it up fine, but incorporating this step into the script itself does not work.

Further troubleshooting and repro may be needed.

**Comment by ryanrichter94** [comment]
Closing as this has only been seen once in testing done thus far.
