### ISSUE TITLE
Update Jenkins and Dotnet-aspnetcoremodule-v2 package versions

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/choco-quickstart-scripts#187]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

Newer versions of the jenkins and dotnet-aspnetcoremodule-v2 package are available.

### Describe The Solution. Why is it needed?

Keep guide as up to date as possible.

**Comment by steviecoaster** [comment]
Fixed in #188
