### ISSUE TITLE
Update Jenkins Jobs for Choco v2 release

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/choco-quickstart-scripts#189]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

Chocolatey v2 changes how `choco list` works. This will be for _local_ packages only. As such, we need to switch Jobs to use `choco search` instead.

### What is Expected?

Jobs work with Chocolatey v2.0.0

### How Did You Get This To Happen?

N/A

### System Details

N/A

### Installed Packages

```bash
N/A
```

### Output Log

```bash
N/A
```

**Comment by ryanrichter94** [comment]
PR was merged. Closing off issue.
