### ISSUE TITLE
Don't internalize and push one-time use packages to Nexus (speed enhancement)

### ISSUE THREAD

**Issue by adilio** [chocolatey/choco-quickstart-scripts#19]
Downloading, internalizing, and pushing one-time use packages is currently taking up quite a bit of setup time.

We need to explore the possibility of cutting down the amount of packages we internalize and push, especially if they will not be reused again.

In initial testing, this can potentially halve the total setup time, from 1 hour to 30 minutes.

**Comment by JPRuskin** [comment]
I had been meaning to ask - why are you internalizing sql-server-express / sql-server-management-studio in here? Surely it's a one time install (to the QDE box), so internalizing like this gains nothing.

**Comment by adilio** [comment]
We used the script from the CCM Setup page initially (https://docs.chocolatey.org/en-us/central-management/setup/#step-1-internalize-packages), to help keep the uniformity of install procedures.

That said, you're right, going forward we don't need to follow this exactly. However, based on testing this in multiple OS's, as well as ensuring enough packages are internalized to support offline install of apps like Chocolatey GUI (with dependencies), we have to remove them gradually, and test after each change.
