### ISSUE TITLE
Script / Documentation for setting up Repositories in Varied Repository Tools

### ISSUE THREAD

**Issue by JPRuskin** [chocolatey/choco-quickstart-scripts#207]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

We should have scripts for setting up the repositories in various different solutions, e.g. standalone Nexus, standalone Artifactory, etc.

### Describe The Solution. Why is it needed?

We should be able to run these scripts with an FQDN and credential and set up the appropriate repositories and accounts for QSG (or a generic C4B solution).

**Comment by ryanrichter94** [comment]
Look to standardize the Jenkins plugins used by all the environments.

**Comment by ryanrichter94** [comment]
Looking at this more I feel this is should be covered as individual third-party repository solution install guides on the docs repository. Not as something within QSG. @JPRuskin please let me know your thoughts.
