### ISSUE TITLE
Add a Nexus Repository Cleanup Task

### ISSUE THREAD

**Issue by JPRuskin** [chocolatey/choco-quickstart-scripts#252]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

Customers will sometimes reach out for help implementing a cleanup policy for their nuget repositories.

We should provide examples or a policy we would be happy with (disabled), so they can quickly and easily enable it for them.

### Describe The Solution. Why is it needed?

A cleanup method with options for customers to configure, allowing them to cleanup old and unwanted package versions.

### Additional Context

Note: A Nexus cleanup task may not meet the needs of our customers. We have had to use a Groovy script instead, as the default cleanup task will delete _all_ old packages, leaving none in place. This may suit some customers, but many prefer to keep the latest package available locally.

Using something like [PhillSwiss' Nexus-Cleanup](https://github.com/PhilSwiss/nexus-cleanup) (or [my modified version](https://gist.github.com/JPRuskin/04726fcbf1b9855acc374ff100b70e07) that I should probably see if the changes can be fed upstream) would allow for this additional functionality.

**Comment by ryanrichter94** [comment]
Feel like this may be better as a doc considering it's not a one fits all solution and may require org specific configuration.

**Comment by steviecoaster** [comment]
We won't be implementing this change, as there's no "one answer" that will satisfy all customers. Instead, we'll document some "recommended" policies, and point to Sonatype documentation on cleanup policy if they wish to create there own outside our select examples
