### ISSUE TITLE
Remove Anisble stuff from README

### ISSUE THREAD

**Issue by steviecoaster** [chocolatey/choco-quickstart-scripts#263]
### Checklist

- [X] I confirm there are no unresolved issues reported on the [Chocolatey Status page](https://status.chocolatey.org).
- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

The README has code for onboarding a client machine with Ansible in it. While useful, it's not meant for this environment.

### What is Expected?

This content doesn't exist.

### How Did You Get This To Happen?

Deploy the guide

### System Details

N/A

### Installed Packages

```bash
N/A
```

### Output Log

```bash
N/A
```

**Comment by JPRuskin** [comment]
I'd like to point out that this is _completely valid_ in every environment.
