### ISSUE TITLE
Hostname change

### ISSUE THREAD

**Issue by mjrcox** [chocolatey/choco-quickstart-scripts#65]
First, thanks for the updated v2 quickstart guide; it really seems to ease complexity of setup. 

However, I am in need of a hostname change in the scripts and in the certificates as I'm not satisfied with the default, which is not detailed in the readme nor on the website. I do find a section on this at the [QDE docs](https://docs.chocolatey.org/en-us/quick-deployment/v1/setup#step-0.1-qde-rename-considerations) so I am assuming the same advice holds for the quickstart setup. Am I assuming this correctly? If so, I would like to suggest adding it to docs here too.

**Comment by adilio** [comment]
Thanks for this feedback, and good point!

As with QDE, hostnames will need to be configured _before_ performing any of the scripting or configuration tasks.

As such, we'd likely include this in Step 0 here, for you to configure before proceeding with the guide:
https://docs.chocolatey.org/en-us/guides/organizations/chocolatey-for-business-quick-start-guide#step-0-preparation-of-c4b-server

Would that address this need as you expected?

**Comment by mjrcox** [comment]
Hi, that could work for others indeed. Although, I just realize I want something slightly different: I want the name used by the endpoints to be some generic 'chocolatey.<some-domain>' domain, which resolves to a CNAME which then points to some A record pointing to the host. The certificates are generated by ourselves so we can take care of that. I'm concerned about all the other places the hostname ends up being hardcoded. Now in the QDE docs I'm reading the following:

> Update client setup scripts that are initialized to the current QDE hostname during setup. You will need to go through the existing scripts in C:/choco-setup/files and replace the default -Hostname value of ALL scripts that have it. Please contact Support if you're unsure how to proceed here.

Considering the quick start v2 uses the same scripts, which I believe they do, I have two options: 

1. Change the -Hostname value as suggested in the initial setup scripts. Not only is this slightly daunting because it is not clear to me how to set the $hostName as opposed to the $domainName variable which are used in conjunction (given we have no AD configured). With this option I'm worried that this will misconfigure something internally where using it's own hostname would be more appropriate, as opposed to our generic DNS resolvable name.    
2. Just run the initial scripts using the default hostname ([System.Net.Dns]::GetHostName()) and then change all the hard coded values in the Nexus scripts which configures the endpoints to Nexus and CCM.

Is this reasoning correct and which of the suggested ways would be advisable?

**Comment by steviecoaster** [comment]
I'm not understanding how this currently isn't handled. We take the hostname from the certificate subject in Set-SSLSecurity, and update the scripts inside of Jenkins for installation to use the subject name from the certificate. So this _should_ be a matter of Running Alternative 2 here: https://docs.chocolatey.org/en-us/guides/organizations/chocolatey-for-business-quick-start-guide#step-4-ssl-setup. 

The onus is on you to make sure that the hostname you use here is resolvable prior to running setup, we could make that more clear I suppose, however there are no code changes required to get your desired behavior.

**Comment by steviecoaster** [comment]
The one area I want to go back and review is Jenkins. We _may_ need to do some work there to ensure these items are accurately updated. But for everything else, the use case is covered with existing documentation/examples.

**Comment by steviecoaster** [comment]
Confirmed that Jenkins will be fine.

**Comment by adilio** [comment]
Hi @mjrcox.

Yes, I see @steviecoaster has already added his voice, and he is correct.

Just to elaborate a bit further, for your benefit.

> Considering the quick start v2 uses the same scripts, which I believe they do

Not exactly. There are some key differences in the scripting that lend to you running it, so I'd caution against that assumption, and also doing any replacement of scripts between the two.

Regarding this quote here:

> Update client setup scripts that are initialized to the current QDE hostname during setup. You will need to go through the existing scripts in C:/choco-setup/files and replace the default -Hostname value of ALL scripts that have it. Please contact Support if you're unsure how to proceed here.

QDE actually makes these changes for you on first-run of the scripts. That's by design. Like QSG, these scripts are intended for a one-time run, and are not idempotent in that you can run them again and again with different values, and expect the right changes to be made.

As we say up top in the QSG, this is an _opinionated_ setup for the time being, and meant to cater to the majority of standard use cases. Anything more customized would be a better conversation for our Customer-focused Support channels. If you're a customer or prospective customer trial'ing C4B, feel free to reach out via that channel, and we'll help you out where we can. 🙂
