### ISSUE TITLE
Add Choco APIKey Entry for ChocolateyInternal Source After SSL is Configured

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/choco-quickstart-scripts#70]
Need to add a choco apikey command to the SSL script right after this line:
https://github.com/chocolatey/choco-quickstart-scripts/blob/63d75120453ce3281dd5e69ea461c5a2ad36f91e/Set-SslSecurity.ps1#L104

Can take this line out of the Nexus script:
https://github.com/chocolatey/choco-quickstart-scripts/blob/63d75120453ce3281dd5e69ea461c5a2ad36f91e/Start-C4bNexusSetup.ps1#L62

**Comment by adilio** [comment]
Sorry Gents, it would appear I was a bit hasty in my pushing Ryan to approve and merge. My bad.

As a result, the API key is currently set _twice in the `Set-SSLSecurity.ps1` script:
https://github.com/chocolatey/choco-quickstart-scripts/blob/ecf1314eec95c89463890ad912e97141b4ec358a/Set-SslSecurity.ps1#L108-L113

Whoops. 😂 

Further to our convo, I am re-opening this issue, and should have a PR up shortly.

Thanks everyone!
