### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by adilio** [chocolatey/choco-quickstart-scripts#91]
I have been able to consistently reproduce a bug with the generation of the `Readme.html` file on the desktop:

```
New-QuickstartReadme : The term 'https://${HostName}:8443' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At C:\choco-setup\files\Start-C4bJenkinsSetup.ps1:177 char:1
+ New-QuickstartReadme
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (https://${HostName}:8443:String) [New-QuickstartReadme], CommandNotFoun
   dException
    + FullyQualifiedErrorId : CommandNotFoundException,New-QuickstartReadme
```

This is called in the `Start-C4bJenkinsSetup.ps1`, and the code for this function is here:
https://github.com/chocolatey/choco-quickstart-scripts/blob/a0feced48042c190a904c24e3b0d5ae6fc123ef2/scripts/Get-Helpers.ps1#L1593-L1637

This error is new, and could be the result of not testing #84 throughly enough?

@steviecoaster , I'm assigning this to you Sir.

**Comment by JPRuskin** [comment]
We've got some new fancy README things, so we'll bring this in line with them.
